---
name: docker image
"on":
  push:
    branch: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # See: https://github.com/docker/build-push-action#leverage-github-cache
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1
      - name: set up cache for docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: log in to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: build and push the buzz alpine image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.alpine
          platforms: linux/amd64
          push: true
          tags: mfontani/buzz:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: build and push the gobuzz alpine image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.goalpine
          platforms: linux/amd64
          push: true
          tags: mfontani/gobuzz:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      # - name: Build the buzz alpine image
      #   #run: docker build --file ./Dockerfile.alpine --tag ghcr.io/mfontani/buzz/alpine .
      #   run: docker build --file ./Dockerfile.alpine --tag mfontani/buzz .
      # - name: Build the gobuzz alpine image
      #   #run: docker build --file ./Dockerfile.goalpine --tag ghcr.io/mfontani/gobuzz/alpine .
      #   run: docker build --file ./Dockerfile.goalpine --tag mfontani/gobuzz .
      #- name: Login to GitHub Package Registry
      #  run: echo "${{ secrets.GH_REGISTRY_RW_PAT }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      #- name: Publish the buzz alpine image
      #  run: docker push ghcr.io/mfontani/buzz/alpine
      #- name: Publish the gobuzz alpine image
      #  run: docker push ghcr.io/mfontani/gobuzz/alpine
      # - name: Login to Docker.io Package Registry
      #   run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_LOGIN }}" --password-stdin
      #- name: Re-tag the buzz alpine image for docker.io
      #  run: docker tag ghcr.io/mfontani/buzz/alpine mfontani/buzz
      #- name: Re-tag the gobuzz alpine image for docker.io
      #  run: docker tag ghcr.io/mfontani/gobuzz/alpine mfontani/gobuzz
      # - name: Publish the buzz alpine image to docker.io
      #   run: docker push mfontani/buzz
      # - name: Publish the gobuzz alpine image to docker.io
      #   run: docker push mfontani/gobuzz
