---
name: docker image
"on":
  push:
    branch: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the alpine image
        run: docker build --file ./Dockerfile.alpine --tag ghcr.io/mfontani/buzz/alpine .
      - name: Login to GitHub Package Registry
        run: echo "${{ secrets.GH_REGISTRY_RW_PAT }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      - name: Publish the alpine image
        run: docker push ghcr.io/mfontani/buzz/alpine
      - name: Login to Docker.io Package Registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_LOGIN }}" --password-stdin
      - name: Re-tag the alpine image for docker.io
        run: docker tag ghcr.io/mfontani/buzz/alpine mfontani/buzz
      - name: Publish the alpine image to docker.io
        run: docker push mfontani/buzz
