---
name: docker image
"on":
  push:
    branch: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # See: https://github.com/docker/build-push-action#leverage-github-cache
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1
      - name: log in to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: build and push the buzz alpine image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.alpine
          platforms: linux/amd64
          pull: true
          push: true
          tags: mfontani/buzz:latest
          build-args: BUILDKIT_INLINE_CACHE=1
          cache-from: mfontani/buzz:latest
      - name: build and push the gobuzz alpine image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.goalpine
          platforms: linux/amd64
          pull: true
          push: true
          tags: mfontani/gobuzz:latest
          build-args: BUILDKIT_INLINE_CACHE=1
          cache-from: mfontani/gobuzz:latest
